### ISSUE TITLE
remove fastify as a dependency.

### ISSUE THREAD

**Issue by mcollina** [google/node-fastify-auto-push#7]
as titled

**Comment by jinwoo** [comment]
Why is this a problem? fastify is a dependency only for the type information, and it'll be removed from the transpiled JavaScript files.

**Comment by mcollina** [comment]
It still is a dependency downloaded from npm. You should move it to devDependencies.

**Comment by jinwoo** [comment]
#8 addresses this. I know it conflicts with #6. I will redo and merge #8 only after #6 is merged.
